network:
  ethernets:
    ens18:
      addresses:
      - 172.16.10.27
      gateway: 172.16.10.1
      nameservers:
        addresses:
        - 172.16.10.1
        search:
        - rushd.serv
  version: 2