## Instalamos todos los paquetes necesarios para
## realizar el cluster de kubernetes

- name: Instalar Docker y Kubernetes
  become: yes
  dnf:
    name: 
      - docker-ce
      - kubeadm
      - kubectl
      - kubelet
    state: present
    disable_excludes: all

## Iniciamos y habilitamos el servicio de Docker en el 
## inico de la VM

- name: Habilitar Docker
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes

## Iniciamos y habilitamos el servicio de Kubelet en el 
## inico de la VM

- name: Habilitar Kubelet
  become: yes
  systemd:
    name: kubelet
    state: started
    enabled: yes

## Instalamos sevidor HTTPD en nodo Master para 
## luego compartir la key y el token para los nodos worker

- name: Instalar HTTPD y GIT en kubemaster
  become: yes
  dnf:
    name:
      - httpd
      - git
    state: present
    disable_excludes: all
  when:
    ansible_eth0.ipv4.address == "10.0.1.10"

## Activamos el demonio HTTPD en nodo Master

- name: Activar HTTPD en kubemaster
  become: yes
  systemd:
    name: httpd
    state: started
    enabled: no
  when:
    ansible_eth0.ipv4.address == "10.0.1.10"

## Configuramos la zona horaria

- name: Configurar Zona horaria
  become: yes
  shell: |
    timedatectl set-timezone Europe/Madrid
    
## Instalamos demonio de tiempo, para sincronizar la fecha

- name: Instalar Chrony
  become: yes
  dnf:
    name:
      - chrony
    state: present
    disable_excludes: all

## Activamos el demonio de tiempo en el inicio

- name: Activar Chrony
  become: yes
  systemd:
    name: chronyd
    state: started
    enabled: yes