## Copiamos los ficheros necesarios para desplegar la aplicaci贸n.

- name: Sincronizar datos para aplicaci贸n en k8s
  copy:
    src: roles/game/files
    dest: /root/
    directory_mode: yes
  when:
    ansible_eth0.ipv4.address == "10.0.1.10"

## Esperamos 15 min hasta que se haya desplegado correctamente
## el cluster rook-ceph

- name: Pausar 15 min para que se despliegue rook
  pause:
    minutes: 15

## Desplegar la aplicaci贸n Game 2048 con su ingress

- name: Desplegar aplicaci贸n Game 2048 bajo ingress
  shell: |
    kubectl apply -f /root/files/game.yml
  when:
    ansible_eth0.ipv4.address == "10.0.1.10"